title:        Gwion
tagline:      A strongly timed musical programming language
paginate:     1

author:
  name:       Jérémie Astor
  url:        https://fennecdjay.github.io/Gwion/

github: [metadata]

gems:
  - jekyll-gist
  - jekyll-paginate
gem: 'github-pages'
markdown: kramdown
incremental: false
gist:
  noscript: false

highlighter: rouge
markdown: kramdown
exclude: [Gemfile.lock, mk_site.sh, .gitignore]

nav_list:
  Home: ['Home']
